/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_taobao_adfs_database_innodb_InnodbJniClient */

#ifndef _Included_com_taobao_adfs_database_innodb_InnodbJniClient
#define _Included_com_taobao_adfs_database_innodb_InnodbJniClient
#ifdef __cplusplus
extern "C" {
#endif

/**
 * javah com.taobao.adfs.database.innodb.InnodbJniClient
 */

/*
 * Class:     com_taobao_adfs_database_innodb_InnodbJniClient
 * Method:    open
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_taobao_adfs_database_innodb_InnodbJniClient_open
  (JNIEnv *, jobject);

/*
 * Class:     com_taobao_adfs_database_innodb_InnodbJniClient
 * Method:    close
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_taobao_adfs_database_innodb_InnodbJniClient_close
  (JNIEnv *, jobject);

/*
 * Class:     com_taobao_adfs_database_innodb_InnodbJniClient
 * Method:    insert
 * Signature: (Ljava/lang/String;Ljava/lang/String;[Ljava/lang/Object;)I
 */
JNIEXPORT jint JNICALL Java_com_taobao_adfs_database_innodb_InnodbJniClient_insert
  (JNIEnv *, jobject, jstring, jstring, jobjectArray);

/*
 * Class:     com_taobao_adfs_database_innodb_InnodbJniClient
 * Method:    find
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;[Ljava/lang/Object;II)Ljava/sql/ResultSet;
 */
JNIEXPORT jobject JNICALL Java_com_taobao_adfs_database_innodb_InnodbJniClient_find
  (JNIEnv *, jobject, jstring, jstring, jstring, jobjectArray, jint, jint);

/*
 * Class:     com_taobao_adfs_database_innodb_InnodbJniClient
 * Method:    delete
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;[Ljava/lang/Object;II)I
 */
JNIEXPORT jint JNICALL Java_com_taobao_adfs_database_innodb_InnodbJniClient_delete
  (JNIEnv *, jobject, jstring, jstring, jstring, jobjectArray, jint, jint);

/*
 * Class:     com_taobao_adfs_database_innodb_InnodbJniClient
 * Method:    update
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;[Ljava/lang/Object;II[Ljava/lang/Object;)I
 */
JNIEXPORT jint JNICALL Java_com_taobao_adfs_database_innodb_InnodbJniClient_update
  (JNIEnv *, jobject, jstring, jstring, jstring, jobjectArray, jint, jint, jobjectArray);

#ifdef __cplusplus
}
#endif
#endif
