/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
package org.apache.hadoop.scribe_log4j.thrift;


public class ResultCode {
  public static final int OK = 0;
  public static final int TRY_LATER = 1;
}
